import Head from "next/head";
import { Inter } from "next/font/google";
import { useLayoutEffect } from "react";
import { useRouter } from "next/router";
import { useAppSelector } from "@/app/lib/store";
import withAuth from "@/hooks/withAuth.hook";

const inter = Inter({ subsets: ["latin"] });

 function Home() {
 const router= useRouter()
  useLayoutEffect(()=>{
   if( localStorage.getItem("authenticatedUser")){
     router.replace('/dashboard')
   }else {
    router.replace('/login')
   }
  },[])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
export default withAuth(Home);
